name: Rust

on:
  push:
    branches: ["logic-development"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: Change to Contracts Directory
        run: cd contracts

      - name: Build
        run: cargo build 
      - name: Run tests
        run: cargo test 
